# Generated by Django 5.2.17 on 2026-09-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Psicologo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=200, verbose_name="nome completo")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
            ],
            options={
                "verbose_name": "psicólogo",
                "verbose_name_plural": "psicólogos",
                "ordering": ["nome_completo", "id"],
            },
        ),
        migrations.CreateModel(
            name="Fila",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                (
                    "psicologo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fila",
                        to="psicologos.psicologo",
                        verbose_name="psicólogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "fila",
                "verbose_name_plural": "filas",
                "ordering": ["psicologo__nome_completo"],
            },
        ),
    ]
