# Generated by Django 5.2.17 on 2026-09-26 15:36

import apps.pacientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(error_messages={'unique': 'Já existe um paciente cadastrado com este CPF. Utilize a busca para localizá-lo.'}, max_length=11, unique=True, validators=[apps.pacientes.validators.validar_cpf], verbose_name='CPF')),
                ('data_nascimento', models.DateField(validators=[apps.pacientes.validators.validar_nascimento], verbose_name='Data de nascimento')),
                ('telefone', models.CharField(max_length=25, validators=[apps.pacientes.validators.validar_telefone], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome_completo'],
            },
        ),
    ]
